### ISSUE TITLE
the test.py failed to run 

### ISSUE THREAD

**Issue by lfxx** [koyeongmin/PINet#1]
got the error below:
Traceback (most recent call last):
  File "C:/Users/gaofeng/Desktop/PINet-master/working.py", line 396, in <module>
    Testing()
  File "C:/Users/gaofeng/Desktop/PINet-master/working.py", line 34, in Testing
    lane_agent = agent.Agent()
  File "C:\Users\gaofeng\Desktop\PINet-master\agent.py", line 35, in __init__
    self.lane_detection_network = lane_detection_network()
  File "C:\Users\gaofeng\Desktop\PINet-master\hourglass_network.py", line 19, in __init__
    self.resizing = resize_layer(3, 128)
  File "C:\Users\gaofeng\Desktop\PINet-master\util_hourglass.py", line 175, in __init__
    self.conv = Conv2D_BatchNorm_Relu(in_channels, out_channels/2, 7, 3, 2)
  File "C:\Users\gaofeng\Desktop\PINet-master\util_hourglass.py", line 35, in __init__
    padding=padding, stride=stride, bias=bias),
  File "C:\Users\gaofeng\Anaconda3\envs\lane_detection\lib\site-packages\torch\nn\modules\conv.py", line 315, in __init__
    False, _pair(0), groups, bias)
  File "C:\Users\gaofeng\Anaconda3\envs\lane_detection\lib\site-packages\torch\nn\modules\conv.py", line 38, in __init__
    out_channels, in_channels // groups, *kernel_size))
TypeError: new() received an invalid combination of arguments - got (float, int, int, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
 * (object data, torch.device device)

any suggestions?@koyeongmin

**Comment by koyeongmin** [comment]
In my opinion, python version is the reason.
We tested the code on python 2.7.
Why don't you refer following link if you are using python3, how about?
https://github.com/tengshaofeng/ResidualAttentionNetwork-pytorch/issues/3
@lfxx

**Comment by lfxx** [comment]
solve it,thanks!
