### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by pyzhang2008** [koyeongmin/PINet#16]
I was trying to test mode 1~3, while it met CUDA error.

Traceback (most recent call last):
  File "test.py", line 388, in <module>
    Testing()
  File "test.py", line 42, in Testing
    lane_agent.load_weights(640, "tensor(0.2298)")
  File "/home/***/PINet/agent.py", line 292, in load_weights
    torch.load(self.p.model_path+str(epoch)+'_'+str(loss)+'_'+'lane_detection_network.pkl'),False
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 729, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 178, in default_restore_location
    result = fn(storage, location)
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 158, in _cuda_deserialize
    return storage_type(obj.size())
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 433, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory

**Comment by koyeongmin** [comment]
It looks like your GPU memory is lack. Could you check this point? In my case, I am using 2080ti, also you can control memory usage by changing batchsize.
