### ISSUE TITLE
test mode error

### ISSUE THREAD

**Issue by gneworld** [koyeongmin/PINet#27]
hi, 
    I met an error when do mode 3 test, error info like this, I don't know why the "j" is just a float so it is not iterable?  thanks very much for your answer

haha@haha-server:~/user/gang/workspace/models/research/PINet$ python2 test.py
Testing
Get dataset
Get agent
Setup GPU mode
Testing loop
evaluate
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
40
Traceback (most recent call last):
  File "test.py", line 411, in <module>
    Testing()
  File "test.py", line 99, in Testing
    evaluation(loader, lane_agent)
  File "test.py", line 110, in evaluation
    x, y = find_target(x, y, target_h, ratio_w, ratio_h)
  File "test.py", line 127, in find_target
    min_y = min(j)
TypeError: 'float' object is not iterable

**Comment by SAIVENKATARAJU** [comment]
Use python 2
