### ISSUE TITLE
numpy version ?

### ISSUE THREAD

**Issue by china56321** [koyeongmin/PINet#28]
**Could you tell me which numpy version did you use ? I use python3.5 to test the my own dataset,meet some problem ,such as :**
Traceback (most recent call last):
  File "test.py", line 388, in <module>
    Testing()
  File "test.py", line 85, in Testing
    _, _, ti = test(lane_agent, np.array([test_image]))
  File "test.py", line 209, in test
    in_x, in_y = util.sort_along_y(in_x, in_y)  
  File "/home/share/make/PINet/util.py", line 222, in sort_along_y
    out_x.append(np.take_along_axis(i, ind[::-1], axis=0).tolist())
**AttributeError: module 'numpy' has no attribute 'take_along_axis'**
**Could you help me to solve this promblem ?  Thanks**

**Comment by koyeongmin** [comment]
I am using 1.16.2 version

**Comment by DK-HU** [comment]
哥们，你解决这个问题了吗
