### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Mkarami3** [koyeongmin/PINet#31]
Hi,
I wanted to thank to you for sharing your code.
I made my data set folders as suggested by the link. But, when I run 
python test.py
it gives me the following error. Could you please suggest a solution for that?
Many thanks

Testing
Get dataset
Get agent
Setup GPU mode
Testing loop
Traceback (most recent call last):
  File "test.py", line 388, in <module>
    Testing()
  File "test.py", line 57, in Testing
    for _, _, _, test_image in loader.Generate():
  File "/home/mohammad/PINet-master/data_loader.py", line 103, in Generate
    self.inputs, self.target_lanes, self.target_h, self.test_image = self.Resize_data(start, end)
  File "/home/mohammad/PINet-master/data_loader.py", line 150, in Resize_data
    ratio_w = self.p.x_size*1.0/temp_image.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Mkarami3** [comment]
Found the solution. The problem was in data set structure.
