### ISSUE TITLE
Error when i train model on my own datasets

### ISSUE THREAD

**Issue by lfxx** [koyeongmin/PINet#8]
Hi,bro,I use 68 points to represent a line in image which size is 1920*1080,but when i train the model,the error occured,the error log is below:
```
Traceback (most recent call last):
  File "/home/longmao/workspace/PINet-master/train.py", line 125, in <module>
    Training()
  File "/home/longmao/workspace/PINet-master/train.py", line 75, in Training
    loss_p = lane_agent.train(inputs, target_lanes, target_h, epoch, lane_agent)
  File "/home/longmao/workspace/PINet-master/agent.py", line 137, in train
    point_loss = self.train_point(inputs, target_lanes, target_h, epoch)
  File "/home/longmao/workspace/PINet-master/agent.py", line 147, in train_point
    ground_truth_point, ground_binary = self.make_ground_truth_point(target_lanes, target_h)
  File "/home/longmao/workspace/PINet-master/agent.py", line 65, in make_ground_truth_point
    ground[batch_index][0][y_index][x_index] = 1.0
IndexError: index 64 is out of bounds for axis 0 with size 64 
```
Seems like that the points is out of boundary ?any suggestions?@koyeongmin

**Comment by lfxx** [comment]
Error occured when the point is on the image boundary,skip these points can reslove.

**Comment by lfxx** [comment]
When i remove the points on image boundary,the issue is solved.
